name: "Run tests on Windows"
description: "Runs the tests on Windows"

inputs:
  working-directory:
    description: "The working directory"
    required: true
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Rust
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: cargo install cargo-nextest --locked

    - name: Install Node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: "18"

    - name: Run tests
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      # FIXME
      env:
        RUST_LOG: worktree=debug,project=debug,git=debug
      run: cargo nextest run -p project test_conflicted_cherry_pick -- --nocapture
      # run: cargo nextest run --workspace --no-fail-fast
