[package]
name = "paths"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/paths.rs"

[features]
remote_server = []

[dependencies]
dirs.workspace = true
util.workspace = true
