[package]
name = "tool_evals"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
assistant2.workspace = true
assistant_tool.workspace = true
assistant_tools.workspace = true
clap.workspace = true
client.workspace = true
collections.workspace = true
context_server.workspace = true
fs.workspace = true
futures.workspace = true
git.workspace = true
gpui.workspace = true
gpui_tokio.workspace = true
language.workspace = true
language_model.workspace = true
language_models.workspace = true
node_runtime.workspace = true
paths.workspace = true
project.workspace = true
prompt_store.workspace = true
rand.workspace = true
reqwest_client.workspace = true
scripting_tool.workspace = true
serde.workspace = true
serde_json_lenient.workspace = true
settings.workspace = true
smol.workspace = true
workspace.workspace = true
