[package]
name = "tool_evals"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
assistant2.workspace = true
fs.workspace = true
gpui.workspace = true
futures.workspace = true
language_model.workspace = true
client.workspace = true
