name: "Build docs"
description: "Build the docs"

runs:
  using: "composite"
  steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2
      with:
        mdbook-version: "0.4.37"

    - name: Cache dependencies
      uses: swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
        cache-provider: "buildjet"

    - name: Install Linux dependencies
      shell: bash -euxo pipefail {0}
      run: ./script/linux

    - name: Install system dependencies
      shell: bash -euxo pipefail {0}
      run: |
        sudo apt-get update
        sudo apt-get install libxkbcommon-dev libxkbcommon-x11-dev

    - name: Limit target directory size
      shell: bash -euxo pipefail {0}
      run: script/clear-target-dir-if-larger-than 100

    - name: Build book
      shell: bash -euxo pipefail {0}
      run: |
        mkdir -p target/deploy
        mdbook build ./docs --dest-dir=../target/deploy/docs/
